Repository depromeet/antoon_web, pull requests merged in 2022-04, with the labels that each got.

#11 ✨ [정책 동의] 체크박스 컴포넌트 추가
  .prettierrc.json
  .storybook/main.js
  components/Policy/Checkbox.stories.tsx
  components/Policy/Checkbox.tsx
  package.json
  pages/index.tsx
  pages/user/oauth/policy.tsx
Labels: enhancement, v0.1, component, setting

#13 🎨 [프로젝트 세팅] husky, lint-staged, npm-run-all 추가
  .husky/.gitignore
  .husky/pre-commit
  .lintstagedrc
  .prettierrc.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  yarn.lock
Labels: setting

#8 ⚙️ [feature] 초기 세팅 추가 설정
  package.json
  yarn.lock
Labels: enhancement, v0.1, setting

#18 [프로젝트 세팅] 노드 버전 추가, 코드 포매팅
  .node-version
  components/Policy/Checkbox.stories.tsx
  components/Policy/Checkbox.tsx
  components/signin/KaKao.style.tsx
  components/signin/Kakao.tsx
  components/signin/Social.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/signin.tsx
  pages/user/oauth/policy.tsx
  styles/GlobalStyle/GlobalStyle.tsx
  yarn.lock
Labels: setting

#3 :fire:[feature] 차트 컴포넌트 추가 및 Lint 설정
  .eslintrc.json
  .gitignore
  .prettierrc.json
  components/Child.tsx
  components/charts/Charts.tsx
  components/charts/chart-utils.ts
  components/charts/composables/Chart_Options.tsx
  components/charts/composables/Chart_Style.json
  components/charts/composables/Charts.style.ts
  components/charts/composables/Charts_Options.ts
  components/charts/composables/ECharts.tsx
  components/icon/Icon.tsx
  components/icon/Icon_Arrow.tsx
  components/icon/Icon_Github.tsx
  components/icon/Icon_Label.tsx
  components/icon/Icon_Star.tsx
  components/icon/Icon_StockUpDown.tsx
  constants/icon-constants.ts
  package.json
  pages/__test__/index.tsx
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/api/hello.ts
  public/favicon.ico
  styles/Theme/emotion.d.ts
  styles/Theme/themes.ts
  tsconfig.json
  tsconfig.paths.json
  types/icon-type.ts
  yarn.lock
Labels: feature, v0.1, component

#24 :bug: [fix] 세팅 오류 해결
  .eslintignore
  .eslintrc.json
  .github/pull_request_template.md
  .prettierignore
  .prettierrc.json
  .storybook/main.js
  .storybook/preview.js
  domains/user/policy/checkbox/Checkbox.stories.tsx
  domains/user/signin/Signin.tsx
  next.config.js
  package.json
  pages/__test__/index.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/index.tsx
  pages/user/signin.tsx
  pages/user/signin/index.tsx
  pages/user/signup/policy.tsx
  styles/globalstyles/GlobalStyle.tsx
  styles/themes/emotion.d.ts
  styles/themes/themes.ts
  tsconfig.paths.json
  types/next-auth.d.ts
  yarn.lock
Labels: bug, v0.1, setting

#25 ✨ [feature] 레이아웃 생성
  assets/svgs/Logo.tsx
  components/layout/Footer.style.tsx
  components/layout/Footer.tsx
  components/layout/Header.style.tsx
  components/layout/Header.tsx
  components/layout/Layout.tsx
  pages/_app.tsx
  pages/index.tsx
  styles/globalstyles/GlobalStyle.tsx
  tsconfig.paths.json
Labels: enhancement, v0.1, component

#27 :fire:[feature #21]: Add Webtoon Detail View Skeleton
  .prettierrc.json
  components/bar/Bar.style.tsx
  components/bar/Bar.tsx
  components/icon/Icon_Heart.tsx
  components/icon/Icon_StockUpDown.tsx
  components/image/Thumbnail.style.tsx
  components/image/Thumbnail.tsx
  components/webtoonDetail/ProInfo.style.tsx
  components/webtoonDetail/ProInfo.tsx
  constants/icon-constants.ts
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
  next.config.js
  pages/__test__/index.tsx
  pages/_app.tsx
  pages/webtoon/[id].tsx
  styles/globalstyles/GlobalStyle.tsx
  styles/themes/themes.ts
  types/webtoon-type.d.ts
Labels: feature, v0.1, component

#28 🔨 [CI/CD] AWS, Chromatic 배포 추가
  .eslintignore
  .github/workflows/deploy.yml
  .gitignore
  .lintstagedrc
  .prettierignore
  .storybook/main.js
  .stylelintrc.json
  components/bar/Bar.style.tsx
  components/image/Thumbnail.style.tsx
  components/layout/Footer.style.tsx
  components/layout/Header.style.tsx
  components/webtoonDetail/ProInfo.style.tsx
  domains/user/signin/kakao/KaKao.style.tsx
  domains/webtoon/detail/Detail.style.tsx
  next.config.js
  package.json
  serverless.yml
  styles/globalstyles/GlobalStyle.tsx
  yarn.lock
Labels: v0.1, setting

#33 🔥 [chore] Next Auth 설정 제거
  domains/user/signin/kakao/Kakao.tsx
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  yarn.lock
Labels: v0.1, component

#32 🔥 [feature] : DetailView Markup And Chart Component
  components/Row.tsx
  components/bar/Bar.style.tsx
  components/bar/Bar.tsx
  components/charts/Charts.tsx
  components/charts/composables/Chart_Options.tsx
  components/charts/composables/Chart_Style.json
  components/charts/composables/Chart_Visualizer.ts
  components/charts/composables/Charts.style.ts
  components/charts/composables/Charts_Options.ts
  components/charts/composables/ECharts.tsx
  components/detail/category/Category.style.tsx
  components/detail/category/CategoryCard.tsx
  components/detail/category/CategorySlider.tsx
  components/detail/tabs/Tabs.style.tsx
  components/detail/tabs/Tabs.tsx
  components/icon/Icon_Back.tsx
  components/image/Thumbnail.style.tsx
  components/webtoonDetail/ProInfo.style.tsx
  components/webtoonDetail/ProInfo.tsx
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
  hooks/useMounted.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/webtoon/[id].tsx
  styles/globalstyles/GlobalStyle.tsx
  types/chart-type.d.ts
  yarn.lock
Labels: enhancement, feature, v0.1, component

#39 :fire:[feature]: Update Detail Main Component
  components/charts/Charts.tsx
  components/charts/chart-utils.ts
  components/charts/composables/Chart_Options.tsx
  components/charts/composables/Chart_Visualizer.ts
  components/detail/tabs/Tabs.style.tsx
  components/detail/tabs/Tabs.tsx
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
  pages/webtoon/[id].tsx
  styles/themes/themes.ts
  types/webtoon-type.d.ts
Labels: feature, v0.1, component

#40 ✨ [상세 페이지] 댓글 컴포넌트 (좋아요 버튼, 사용자 프로필 사진) 생성
  .storybook/preview.js
  assets/svgs/Search.tsx
  components/button/FavoriteBtn.stories.tsx
  components/button/FavoriteBtn.tsx
  components/icon/Icon_Heart.tsx
  components/image/UserProfile.style.tsx
  components/image/UserProfile.tsx
  domains/webtoon/detail/Comment.data.ts
  domains/webtoon/detail/Comment.style.tsx
  domains/webtoon/detail/Comment.tsx
  next.config.js
  package.json
  styles/globalstyles/GlobalStyle.tsx
Labels: feature, v0.1, component

#41 ✨ [홈 페이지] 레이아웃 구성 / 디자인 적용 (UT 버전)
  components/carousel/Carousel.style.tsx
  domains/webtoon/home/Genres.style.tsx
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/Home.tsx
  domains/webtoon/home/Popular.style.tsx
  domains/webtoon/home/RealTimeChart.style.tsx
  domains/webtoon/home/RealTimeChart.tsx
  domains/webtoon/home/Recommendation.style.tsx
  domains/webtoon/home/Weekly.style.tsx
  styles/themes/themes.ts
Labels: feature, design

#45 ✨ [공통 컴포넌트] 레이아웃 생성
  assets/svgs/Logo.tsx
  assets/svgs/Search.tsx
  components/detail/tabs/Tabs.style.tsx
  components/icon/Icon_Back.tsx
  components/layout/Footer.style.tsx
  components/layout/Footer.tsx
  components/layout/Header.style.tsx
  components/layout/Header.tsx
  components/layout/Layout.tsx
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/Home.tsx
  pages/_app.tsx
  pages/index.tsx
  pages/user/signin.tsx
  pages/user/signup/policy.tsx
  pages/webtoon/[id].tsx
  public/favicon.ico
  styles/globalstyles/GlobalStyle.tsx
  styles/themes/themes.ts
Labels: v0.1, component

#46 ✨ [검색] 검색 기능 구현
  assets/svgs/DeleteIcon.tsx
  assets/svgs/Logo.tsx
  assets/svgs/SearchIcon.tsx
  components/icon/BackIcon.tsx
  components/icon/Icon_Back.tsx
  components/layout/Header.style.tsx
  components/layout/Header.tsx
  components/layout/Layout.tsx
  components/layout/SearchBar.style.tsx
  components/layout/SearchBar.tsx
  domains/search/Search.data.ts
  domains/search/Search.style.tsx
  domains/search/Search.tsx
  domains/webtoon/detail/Comment.data.ts
  domains/webtoon/detail/Comment.tsx
  hooks/.gitkeep
  hooks/useAutoComplete.ts
  pages/search.tsx
  states/.gitkeep
  states/search.ts
  styles/globalstyles/GlobalStyle.tsx
  styles/themes/themes.ts
Labels: feature, v0.1, component
