Repository depromeet/antoon_web, pull requests merged in 2022-06, with the labels that each got.

#102 🐛 [검색] URL 직접 접근 버그 해결
  domains/search/AutoCompletList.tsx
  domains/search/Search.tsx
  domains/webtoon/detail/Detail.style.tsx
  pages/search.tsx
  tsconfig.paths.json
Labels: bug, enhancement, v0.1

#104 🔒️ [사용자 인증] access 토큰 디폴트 헤더 설정
  apis/api.ts
  apis/comments.ts
  apis/queryKeys.ts
  apis/webtoons.ts
  components/layout/Header/HeaderRightMenu.tsx
  domains/search/AutoCompletList.tsx
  domains/search/Search.tsx
  domains/webtoon/detail/Detail.style.tsx
  package.json
  pages/user/signin.tsx
  yarn.lock
Labels: enhancement, feature, v0.1

#106 :fire:[feature] 상세 데이터페칭 업데이트 및 차트 로직 추가
  apis/queryKeys.ts
  apis/webtoons.ts
  components/charts/Charts.tsx
  components/charts/chart-utils.ts
  components/charts/composables/Chart_Visualizer.ts
  components/detail/button/BtnFooter.style.tsx
  components/detail/button/BtnFooter.tsx
  components/detail/button/Toast.style.tsx
  components/detail/button/Toast.tsx
  components/detail/button/UpDownBtn.tsx
  components/detail/tabs/Tabs.tsx
  components/modal/detail/Modal.style.tsx
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
  hooks/useCountdown.ts
  styles/themes/themes.ts
  types/chart-type.d.ts
  types/webtoon-type.d.ts
  utils/date-util.ts
  utils/string-util.ts
Labels: v0.1, component

#107 ♻️ [상세 페이지] 스타일린트 에러 해결
  components/detail/button/BtnFooter.style.tsx
  components/detail/button/Toast.style.tsx
  domains/webtoon/detail/Detail.style.tsx
Labels: bug, v0.1

#108 ✨ [홈 페이지] 프리패치에서 클라이언트로 패치로 변경
  apis/webtoons.ts
  components/spinner/LoadingSpinner.tsx
  domains/webtoon/home/Genres.tsx
  domains/webtoon/home/RealTimeChart.tsx
  domains/webtoon/home/Recommendation.tsx
  domains/webtoon/home/Rising.tsx
  package.json
  pages/index.tsx
  yarn.lock
Labels: enhancement, v0.1

#109 :fire:[feature] 디테일 마크업 최종 & 탑승하차 로직 스켈레톤
  apis/queryKeys.ts
  apis/webtoons.ts
  assets/icons/Icon.tsx
  assets/icons/StockIcon.tsx
  components/charts/composables/Chart_Visualizer.ts
  components/detail/button/BtnFooter.tsx
  components/detail/button/Toast.style.tsx
  components/detail/button/Toast.tsx
  components/detail/tabs/Tabs.style.tsx
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
  types/webtoon-type.d.ts
Labels: v0.1, component

#111 🔍️ [SEO] Robots, Sitemap 설정
  next-sitemap.config.js
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  yarn.lock
Labels: enhancement, v0.1, setting

#114 🐛 [홈] 요일별 웹툰의 요일 선택을 올바르게 표시함
  domains/webtoon/home/Weekly.style.tsx
  domains/webtoon/home/Weekly.tsx
Labels: bug, v0.1

#110 :fire:[feature] : 댓글 post 기능 완료
  apis/api.ts
  apis/comments.ts
  apis/queryKeys.ts
  apis/user.ts
  apis/webtoons.ts
  components/detail/button/BtnFooter.tsx
  components/detail/commentTextInput/CommentTextInput.style.tsx
  components/detail/commentTextInput/CommentTextInput.tsx
  components/modal/detail/Modal.tsx
  domains/webtoon/detail/Comment.style.tsx
  domains/webtoon/detail/Comment.tsx
  domains/webtoon/detail/Detail.tsx
  types/webtoon-type.d.ts
Labels: v0.1, component

#118 💄 [에러 바운더리] 텍스트 CSS 수정
  components/ErrorBoundary.tsx
Labels: v0.1, chore

#124 ✨ [마이페이지] 사용자 이름 수정
  apis/user.ts
  assets/icons/CommentEditIcon.tsx
  assets/icons/DeleteIcon.tsx
  assets/icons/ProfileNameEdit.tsx
  domains/search/SearchBar.tsx
  domains/user/mypage/UserName.style.tsx
  domains/user/mypage/UserName.tsx
  domains/user/mypage/edit/EditName.style.tsx
  domains/user/mypage/edit/EditName.tsx
  pages/user/mypage/edit.tsx
Labels: enhancement, feature, v0.1

#126 :bug: [마이페이지] 로그아웃 에러 수정
  apis/queryKeys.ts
  apis/user.ts
  domains/user/mypage/MyPage.tsx
  domains/webtoon/detail/Comment.data.ts
Labels: bug, v0.1

#128 :recycle: [레이아웃] Header 사용자 데이터 API 변경
  components/layout/Header/Header.tsx
  components/layout/Header/HeaderLeftMenu.tsx
  components/layout/Header/HeaderRightMenu.style.tsx
  components/layout/Header/HeaderRightMenu.tsx
  pages/community/topic/[id].tsx
  pages/index.tsx
Labels: bug, v0.1

#129 :fire:[feature] : A/B테스트/모달, 공통 컴포넌트 마크업 기능 작성
  assets/icons/CheckIcon.tsx
  assets/icons/antcoin.svg
  assets/icons/antcoin_sm.svg
  assets/icons/index.ts
  components/button/VoteBtn.style.tsx
  components/button/VoteBtn.tsx
  components/chip/VoteChip.style.tsx
  components/chip/VoteChip.tsx
  components/detail/button/BtnFooter.style.tsx
  components/detail/button/BtnFooter.tsx
  components/modal/detail/Modal.tsx
  components/modal/vote/Modal.style.tsx
  components/modal/vote/Modal.tsx
  components/timecounter/TimeCounter.style.tsx
  components/timecounter/TimeCounter.tsx
  components/vote/ABVoteItem.style.tsx
  components/vote/ABVoteItem.tsx
  components/vote/VoteHeader.style.tsx
  components/vote/VoteHeader.tsx
  domains/community/topic/ABVote.style.tsx
  domains/community/topic/ABVote.tsx
  domains/community/topic/ChoiceVote.tsx
  domains/community/topic/VoteDetail.tsx
  domains/webtoon/detail/Detail.tsx
  hooks/useCountdown.ts
  types/vote-type.ts
  utils/date-util.ts
  utils/num-util.ts
Labels: feature, v0.2, component

#130 :fire:[fix]: 상세 캐러셀 margin, 폰트 사이즈, null값 에러 버그 Fix
  components/detail/category/Category.style.tsx
  domains/webtoon/detail/Detail.tsx
Labels: bug, v0.2, component

#131 :fire:[feature]: 초이스 투표 마크업 구현 및 timecounter 버그 fix
  assets/icons/CheckIcon.tsx
  components/detail/button/BtnFooter.tsx
  components/timecounter/TimeCounter.tsx
  components/vote/ChiceVoteItem.tsx
  components/vote/ChoiceVoteItem.style.tsx
  components/vote/VoteHeader.style.tsx
  components/vote/VoteHeader.tsx
  domains/community/topic/ChoiceVote.style.tsx
  domains/community/topic/ChoiceVote.tsx
  domains/community/topic/VoteDetail.tsx
Labels: bug, enhancement, feature, v0.2, component

#132 :bug: [투표] 빌드 에러 해결
  components/vote/ABVoteItem.tsx
Labels: bug, v0.1

#134 🚑️ [로그아웃] 토큰 도메인 수정
  domains/user/mypage/MyPage.tsx
Labels: bug, v0.1

#133 :fire:[feature]: 투표 A/B, 초이스 결과 마크업 완료
  assets/icons/crown.svg
  assets/icons/index.ts
  components/vote/ABVoteItem.style.tsx
  components/vote/ABVoteItem.tsx
  components/vote/ChiceVoteItem.tsx
  components/vote/ChoiceVoteItem.style.tsx
  domains/community/topic/ABVote.tsx
  domains/community/topic/ChoiceVote.tsx
  domains/community/topic/VoteDetail.tsx
Labels: feature, v0.2, component

#136 [fix]: issue_11 해결 (툴팁 svg 변경)
  assets/icons/index.ts
  assets/icons/tooltip.svg
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
Labels: bug, enhancement, v0.2, design

#137 🚑️ [로그아웃] 토큰 도메인 수정
  domains/user/mypage/MyPage.tsx
Labels: bug, v0.1

#138 🚑️ [로그아웃] 토큰 도메인 .antoon.fun 수정
  domains/user/mypage/MyPage.tsx
Labels: bug, v0.1

#139 ✨ [마이페이지] 2차 MVP 마이페이지
  assets/banners/MyPageBanner.tsx
  assets/banners/index.ts
  assets/banners/mypage_banner.svg
  assets/icons/ProfileNameEdit.tsx
  assets/icons/UserBadgeIcon.tsx
  assets/icons/coin_status_arrow.svg
  assets/icons/index.ts
  assets/icons/mypage_coin.svg
  assets/icons/profile_img_edit.svg
  assets/images/ProfileDefaultImg.tsx
  domains/user/mypage/DefaultMyPage.tsx
  domains/user/mypage/MyPage.style.tsx
  domains/user/mypage/MyPage.tsx
  domains/user/mypage/MyPageMenu.style.tsx
  domains/user/mypage/MyPageMenu.tsx
  domains/user/mypage/SigninBtn.style.tsx
  domains/user/mypage/SigninBtn.tsx
  domains/user/mypage/SignoutBtn.style.tsx
  domains/user/mypage/SignoutBtn.tsx
  domains/user/mypage/UserBadge.style.tsx
  domains/user/mypage/UserBadge.tsx
  domains/user/mypage/UserCoin.style.tsx
  domains/user/mypage/UserCoin.tsx
  domains/user/mypage/UserData.style.tsx
  domains/user/mypage/UserData.tsx
  domains/user/mypage/UserName.style.tsx
  domains/user/mypage/UserName.tsx
  domains/user/mypage/edit/EditImg.style.tsx
  domains/user/mypage/edit/EditImg.tsx
  domains/user/mypage/edit/EditName.style.tsx
  domains/user/mypage/edit/EditName.tsx
  domains/user/signup/policy/Checkbox.stories.tsx
  domains/user/signup/policy/Checkbox.tsx
  next.config.js
  pages/user/mypage.tsx
  pages/user/mypage/edit.tsx
  pages/user/signup/policy.tsx
  types/comments-type.ts
  types/user-type.ts
Labels: enhancement, feature, v0.2, component

#140 ✨ [레이아웃] 2차 MVP 레이아웃
  assets/icons/FooterCommunityIcon.tsx
  assets/icons/FooterHomeIcon.tsx
  assets/icons/FooterMyPageIcon.tsx
  assets/icons/ShareIcon.tsx
  components/layout/Header/Header.stories.tsx
  components/layout/Header/Header.style.tsx
  components/layout/Header/Header.tsx
  components/layout/Header/HeaderLeftMenu.tsx
  components/layout/Header/HeaderRightMenu.style.tsx
  components/layout/Header/HeaderRightMenu.tsx
  components/layout/Layout.style.tsx
  components/layout/Layout.tsx
  domains/user/mypage/UserData.style.tsx
  domains/user/mypage/UserData.tsx
  pages/community/topic/[id].tsx
  pages/index.tsx
  pages/user/mypage.tsx
  pages/user/mypage/edit.tsx
  pages/user/signin.tsx
  pages/user/signup/policy.tsx
  pages/webtoon/[id].tsx
  styles/GlobalStyle.tsx
Labels: enhancement, feature, v0.2, component

#141 ✨ [커뮤니티] 커뮤니티 탭 마크업
  apis/queryKeys.ts
  apis/topics.ts
  apis/webtoons.ts
  components/SubTitle.tsx
  components/Title.tsx
  components/button/TagBtn.stories.tsx
  components/button/TagBtn.tsx
  components/chip/VoteChip.style.tsx
  components/chip/VoteChip.tsx
  components/vote/VoteHeader.style.tsx
  domains/community/AllTopics.tsx
  domains/community/Community.style.tsx
  domains/community/topic/AllTopicCards.style.tsx
  domains/community/topic/AllTopicCards.tsx
  domains/community/topic/TopicCards.style.tsx
  domains/community/topic/TopicCards.tsx
  domains/community/topic/TopicCategroyButtons.style.tsx
  domains/community/topic/VoteDetail.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartTitle.tsx
  pages/_app.tsx
  pages/community.tsx
  types/topics-type.d.ts
  types/vote-type.ts
Labels: feature, v0.2, component

#142 [feature]: 댓글 공통화 및 적용 완료 & css 여럿 수정
  apis/comments.ts
  apis/queryKeys.ts
  apis/topics.ts
  components/detail/button/UpDownBtn.style.tsx
  components/detail/commentTextInput/CommentTextInput.style.tsx
  components/detail/commentTextInput/CommentTextInput.tsx
  components/modal/detail/Modal.style.tsx
  components/modal/vote/Modal.style.tsx
  components/modal/vote/Modal.tsx
  components/vote/ABVoteItem.style.tsx
  components/vote/ABVoteItem.tsx
  components/vote/ChiceVoteItem.tsx
  components/vote/VoteHeader.tsx
  domains/community/topic/ABVote.tsx
  domains/community/topic/ChoiceVote.tsx
  domains/community/topic/VoteDetail.tsx
  domains/webtoon/detail/Comment.style.tsx
  domains/webtoon/detail/Comment.tsx
  domains/webtoon/detail/Detail.tsx
  pages/community/topic/[id].tsx
  pages/webtoon/[id].tsx
  types/comments-type.ts
  types/vote-type.ts
Labels: feature, v0.2, component

#145 :fire:[feature]: vote api연동 및 테스트
  components/modal/vote/Modal.tsx
  components/vote/ABVoteItem.style.tsx
  components/vote/ABVoteItem.tsx
  components/vote/VoteHeader.tsx
  domains/community/topic/ABVote.tsx
  domains/community/topic/ChoiceVote.tsx
  domains/community/topic/VoteDetail.tsx
Labels: feature, v0.2, component

#146 ✨ [회원가입] 코인 지급 모달
  assets/icons/index.ts
  assets/icons/signup_coin_introduce.svg
  domains/user/mypage/MyPage.style.tsx
  domains/user/mypage/MyPage.tsx
  domains/user/mypage/SigninBtn.style.tsx
  domains/user/mypage/SigninBtn.tsx
  domains/user/mypage/UserBadge.style.tsx
  domains/user/mypage/UserBadge.tsx
  domains/user/mypage/edit/EditName.style.tsx
  domains/user/signin/SignInMain.style.tsx
  domains/user/signup/modal/CoinModal.style.tsx
  domains/user/signup/modal/CoinModal.tsx
  next.config.js
  pages/_app.tsx
  pages/index.tsx
  public/images/loginpage_bg.png
  public/images/signin_01.png
  public/images/signin_02.png
  public/images/signin_03.png
  types/user-type.ts
Labels: enhancement, feature, v0.2, component

#147 ✨ [홈] 토픽 배너 및 mvp 2차 마크업
  components/button/TagBtn.tsx
  domains/community/Community.style.tsx
  domains/community/topic/AllTopicCards.style.tsx
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/Home.tsx
  domains/webtoon/home/TopicBanners.style.tsx
  domains/webtoon/home/TopicBanners.tsx
Labels: v0.2, component, design

#149 ✨ [마이페이지] 뱃지 정보 모달
  assets/icons/badge_level_1.svg
  assets/icons/badge_level_2.svg
  assets/icons/badge_level_3.svg
  assets/icons/index.ts
  assets/icons/modal_close.svg
  domains/user/mypage/BadgeInfoModal.style.tsx
  domains/user/mypage/BadgeInfoModal.tsx
  domains/user/mypage/UserBadge.tsx
  domains/webtoon/detail/Comment.tsx
Labels: v0.2, component, design

#148 :fire:[feature]: 토스트 분리 및 탑승하차 테스트(1)
  apis/webtoons.ts
  assets/icons/antcoin_bg.svg
  assets/icons/index.ts
  components/charts/Charts.tsx
  components/charts/composables/Chart_Visualizer.ts
  components/detail/button/BtnFooter.style.tsx
  components/detail/button/BtnFooter.tsx
  components/modal/detail/Modal.style.tsx
  components/modal/detail/Modal.tsx
  components/timecounter/TimeCounter.style.tsx
  components/timecounter/TimeCounter.tsx
  components/toast/Toast.style.tsx
  components/toast/Toast.tsx
  components/toast/ToastList.tsx
  domains/webtoon/detail/Comment.style.tsx
  domains/webtoon/detail/Comment.tsx
  domains/webtoon/detail/Detail.tsx
  hooks/useToast.ts
  pages/_app.tsx
  stores/toast.tsx
  tsconfig.paths.json
  types/webtoon-type.d.ts
  utils/string-util.ts
Labels: feature, v0.2, component

#151 🍡 [feature]: toast 웹툰 상세, 투표페이지 적용
  apis/webtoons.ts
  assets/icons/alert_line.svg
  assets/icons/index.ts
  components/button/VoteBtn.tsx
  components/detail/button/BtnFooter.tsx
  components/detail/commentTextInput/CommentTextInput.style.tsx
  components/detail/commentTextInput/CommentTextInput.tsx
  components/modal/detail/Modal.tsx
  components/modal/vote/Modal.tsx
  components/toast/Toast.style.tsx
  components/toast/Toast.tsx
  components/toast/ToastList.tsx
  stores/toast.tsx
Labels: feature, v0.2, component

#152 :fire:[fix]: css 수정 및 통합테스트 완료
  assets/icons/alert_line.svg
  assets/icons/index.ts
  components/button/VoteBtn.style.tsx
  components/button/VoteBtn.tsx
  components/detail/button/UpDownBtn.style.tsx
  components/detail/commentTextInput/CommentTextInput.style.tsx
  components/detail/commentTextInput/CommentTextInput.tsx
  components/modal/detail/Modal.tsx
  components/modal/vote/Modal.tsx
  components/toast/Toast.style.tsx
  components/toast/Toast.tsx
  domains/community/topic/VoteDetail.tsx
  domains/webtoon/detail/Detail.tsx
  public/images/alert_line.png
  types/vote-type.ts
Labels: bug, v0.2, design

#154 [Fix] : 상세 로그인 에러 핸들링 추가
  components/button/VoteBtn.tsx
  components/detail/button/UpDownBtn.tsx
  components/detail/commentTextInput/CommentTextInput.style.tsx
  components/detail/commentTextInput/CommentTextInput.tsx
  components/toast/Toast.tsx
  stores/toast.tsx
Labels: enhancement, v0.2

#155 Update/readme
  README.md
  public/main.gif
Labels: documentation, feature, v0.2

#153 ✨ [ 홈/커뮤니티] 홈 배너 및 웹툰 랭킹 커뮤니티 페이지에서 사용
  apis/queryKeys.ts
  apis/topics.ts
  apis/webtoons.ts
  components/Title.tsx
  domains/community/ranks/CommunityRanks.tsx
  domains/community/ranks/CommunityRanksCards.tsx
  domains/community/topic/AllTopicCards.style.tsx
  domains/community/topic/AllTopicCards.tsx
  domains/community/topic/TopicCards.style.tsx
  domains/community/topic/TopicCards.tsx
  domains/community/topic/TopicCategroyButtons.style.tsx
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/Home.tsx
  domains/webtoon/home/TopicBanners.style.tsx
  domains/webtoon/home/TopicBanners.tsx
  domains/webtoon/home/realTimeChart/CharacterJoinButton.tsx
  domains/webtoon/home/realTimeChart/RealTimeChart.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartCharacters.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartTitle.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.style.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.tsx
  pages/community.tsx
  pages/community/ranks.tsx
  types/topics-type.d.ts
  types/webtoon-type.d.ts
Labels: feature, v0.2, component

#156 [fix]: 최종 merge
  apis/queryKeys.ts
  apis/topics.ts
  domains/community/topic/AllTopicCards.tsx
  types/topics-type.d.ts
Labels: bug, v0.2

#157 [feature]: 인물/투표 댓글 컴포넌트 추가
  domains/community/character/CharacterDetailPage.style.tsx
  domains/community/character/CharacterPageCountDown.style.tsx
  domains/webtoon/detail/Comment.style.tsx
  pages/community/character/[id].tsx
  types/comments-type.ts
Labels: enhancement, feature, v0.2, component

#159 [feature]: 실시간 차트 타임카운터 추가
  domains/community/character/CharacterPageCountDown.tsx
  domains/community/ranks/CommunityRanks.style.tsx
  domains/community/ranks/CommunityRanks.tsx
  domains/webtoon/home/Home.style.tsx
Labels: enhancement, feature, v0.2

#160 🐛 [배포] 메인 브랜치 lint 배포 오류 수정
  domains/community/ranks/CommunityRanks.style.tsx
Labels: bug, v0.2, chore

#161 ✨ [QA] QA 대응 및 세부적인 내용 수정
  README.md
  assets/icons/email.svg
  assets/icons/index.ts
  components/button/FloatingBtn.tsx
  components/layout/Header/Header.tsx
  components/layout/Header/HeaderLeftMenu.tsx
  components/layout/Header/HeaderRightMenu.tsx
  components/layout/Layout.style.tsx
  components/toast/ToastList.tsx
  domains/user/mypage/BadgeInfoModal.tsx
  domains/user/mypage/MyPage.style.tsx
  domains/user/mypage/UserBadge.style.tsx
  domains/user/mypage/UserBadge.tsx
  domains/user/mypage/UserCoin.style.tsx
  hooks/useScroll.ts
  pages/_app.tsx
  public/favicon.ico
  public/main.gif
  styles/GlobalStyle.tsx
Labels: enhancement, v0.2

#162 🐛 [버그] 세부적인 버그 픽스
  components/detail/button/BtnFooter.style.tsx
  components/layout/Header/HeaderLeftMenu.tsx
  components/layout/Header/HeaderRightMenu.tsx
  domains/user/mypage/UserBadge.tsx
  domains/user/signup/modal/CoinModal.tsx
  domains/webtoon/detail/Comment.style.tsx
  pages/index.tsx
  pages/user/signin.tsx
Labels: bug, v0.2

#163 🐛 [회원가입] 모달 status 값 변경
  domains/user/signup/modal/CoinModal.tsx
  pages/index.tsx
  pages/user/signin.tsx
Labels: bug, v0.2

#164 🎨 [커뮤니티] qa 마크업 적용
  domains/community/ranks/CommunityRanks.style.tsx
  domains/community/ranks/CommunityRanksCards.tsx
  domains/community/topic/AllTopicCards.tsx
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartCharacters.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartTitle.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.tsx
  pages/community.tsx
Labels: enhancement, v0.2

#165 [홈/커뮤니티] CLS 대응
  domains/community/topic/AllTopicCards.style.tsx
  domains/community/topic/AllTopicCards.tsx
  domains/webtoon/home/WeeklyWebtoons.tsx
  pages/user/signin.tsx
Labels: bug, enhancement, v0.2

#167 [fix]: css 디테일 수정 작업
  components/bar/Bar.tsx
  components/modal/detail/Modal.tsx
Labels: bug, enhancement, v0.2

#166 ✨ [인물/커플 상세페이지] 데이터 API 연동
  apis/queryKeys.ts
  apis/webtoons.ts
  components/button/FloatingBtn.tsx
  components/layout/Header/Header.style.tsx
  components/layout/Header/Header.tsx
  domains/community/character/CharacterDetailPage.style.tsx
  domains/community/character/CharacterDetailPage.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartCharacters.tsx
  hooks/useScroll.ts
  pages/community/character/[id].tsx
  types/webtoon-type.d.ts
Labels: feature, v0.2

#168 [홈] 랭킹 마진 조정
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/WeeklyWebtoons.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.style.tsx
Labels: v0.2, design

#169 🎨[홈] 배너 마크업 조정
  domains/community/topic/AllTopicCards.style.tsx
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartTitle.tsx
  domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.style.tsx
Labels: bug, v0.2, design

#170 [Hotfix]-css 1
  components/modal/detail/Modal.style.tsx
Labels: bug, enhancement, v0.2

#171 Hotfix/css my page
  components/layout/Layout.style.tsx
  domains/user/mypage/MyPage.style.tsx
Labels: bug, feature, v0.2

#172 Hotfix/css navi
  components/layout/Layout.style.tsx
  components/layout/Layout.tsx
Labels: bug, enhancement, feature, v0.2

#173 Hotfix/css my page2
  domains/user/mypage/MyPage.style.tsx
  domains/user/mypage/SigninBtn.style.tsx
Labels: bug, enhancement, v0.2

#174 [hotfix]: 투표 에러핸들링
  components/button/VoteBtn.tsx
  components/vote/ABVoteItem.tsx
  domains/community/topic/ABVote.tsx
Labels: bug, feature, v0.2

#175 [온보딩] mvp2차 온보딩 추가
  components/modal/onboard/Modal.tsx
  public/images/onboarding_introduce_02.png
  public/images/onboarding_introduce_03.png
  public/images/onboarding_introduce_04.png
  public/images/onboarding_introduce_05.png
Labels: feature, v0.2

#176 [웹툰 상세] 웹툰 상세 단위 변경
  domains/webtoon/detail/Detail.tsx
Labels: enhancement, v0.2

#177 [웹툰 상세] 웹툰 상세 단위 대문자로 변경
  domains/webtoon/detail/Detail.tsx
Labels: bug, v0.2
