Repository depromeet/antoon_web, pull requests merged in 2022-08, with the labels that each got.

#200 🚑 [프로젝트 세팅] PR 생성 시 ci/cd 작동 추가 및 빌드 에러 수정
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_stg_and_prd.yml
  domains/webtoon/detail/Detail.tsx
Labels: bug, chore

#197 💄 [메인페이지] 피드백 버튼
  assets/icons/email.svg
  components/button/FloatingBtn.tsx
Labels: v0.2, design

#204 🩹 [마이페이지] 사용자 이름 수정하기 버그 픽스
  domains/user/mypage/UserData.style.tsx
  domains/user/mypage/UserData.tsx
Labels: v0.2, chore

#205 ♻️ [마이페이지] state로 분기 처리
  pages/user/mypage.tsx
Labels: v0.2, chore

#206 💄 [메인페이지] 피드백 버튼 위치 수정
  components/button/FloatingBtn.tsx
Labels: v0.2, chore, design

#207 🐛 [로그아웃] user data invalidate 설정
  apis/user.ts
Labels: bug, v0.2

#195 🔥 [feature] : 댓글 observer 기반 무한스크롤 구현, 댓글 QA 스피너 훌라후프 현상 해결
  apis/comments.ts
  apis/queryKeys.ts
  domains/webtoon/detail/Comment.style.tsx
  domains/webtoon/detail/Comment.tsx
  package.json
  public/sitemap-0.xml
  yarn.lock
Labels: enhancement, feature, v0.2

#209 🐛 [마이페이지] 로그인 여부 체크 조건 업데이트
  pages/user/mypage.tsx
Labels: bug, v0.2

#210 🩹 [프로젝트 세팅] html lang 설정 변경
  pages/_app.tsx
  pages/_document.tsx
Labels: bug

#211 🔧 [프로젝트 세팅] github actions dependencies cache 체크 변경
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_stg_and_prd.yml
Labels: bug, chore

#213 ✨ [ 웹툰 토픽] 메인 페이지 개미들의 선택 섹션 항목 클릭 시 토픽 페이지로 이동
  domains/community/topic/TopicCards.style.tsx
  domains/community/topic/TopicCards.tsx
Labels: feature, v0.2

#214 ✨ [장르별 웹툰] 장르별 웹툰 페이지 추가
  apis/queryKeys.ts
  apis/webtoons.ts
  assets/icons/index.ts
  assets/icons/kakao.svg
  assets/icons/naver.svg
  components/button/TagBtn.tsx
  domains/community/ranks/CommunityRanksCards.tsx
  domains/genres/GenreWebtoons.style.tsx
  domains/genres/GenreWebtoons.tsx
  domains/webtoon/home/Genres.style.tsx
  domains/webtoon/home/Genres.tsx
  domains/webtoon/home/Recommendation.stories.tsx
  domains/webtoon/home/Recommendation.tsx
  pages/community.tsx
  pages/genres.tsx
  types/webtoon-type.ts
Labels: feature, v0.2

#215 ✨ [헤더] URL 공유하기 버튼
  components/button/BackBtn.tsx
  components/button/ShareBtn.tsx
  components/layout/Header/Header.tsx
  components/layout/Header/HeaderLeftMenu.tsx
  components/layout/Header/HeaderRightMenu.tsx
  hooks/useMounted.ts
  hooks/useSmoothScroll.ts
  pages/_app.tsx
  pages/community/character/[id].tsx
  pages/community/topic/[id].tsx
  pages/webtoon/[id].tsx
  utils/shareAPI.ts
Labels: feature, v0.2

#219 ✨ [마이페이지] 안트코인 내역
  apis/queryKeys.ts
  apis/user.ts
  assets/icons/chebron-right-white.svg
  assets/icons/index.ts
  components/button/VoteBtn.tsx
  components/detail/button/UpDownBtn.tsx
  components/detail/commentTextInput/CommentTextInput.tsx
  components/modal/coin/NotEnoughCoin.tsx
  components/modal/detail/Modal.tsx
  components/modal/vote/Modal.tsx
  domains/community/character/CharacterDetailPage.tsx
  domains/user/mypage/MyPage.tsx
  domains/user/mypage/coin/Coin.style.tsx
  domains/user/mypage/coin/Coin.tsx
  domains/user/mypage/coin/CoinGuideModal.style.tsx
  domains/user/mypage/coin/CoinGuideModal.tsx
  domains/user/mypage/coin/CoinHistory.style.tsx
  domains/user/mypage/coin/CoinHistory.tsx
  domains/user/mypage/coin/CoinUsage.style.tsx
  domains/user/mypage/coin/CoinUsage.tsx
  domains/user/mypage/edit/EditImg.tsx
  domains/user/mypage/signout/SignoutModal.tsx
  domains/user/signup/modal/CoinModal.tsx
  domains/webtoon/detail/Comment.tsx
  pages/user/mypage/coins.tsx
  pages/user/mypage/edit.tsx
  pages/user/mypage/index.tsx
  types/user-type.ts
Labels: feature, v0.2
