Repository depromeet/antoon_web, pull requests merged in 2022-07, with the labels that each got.

#178 🩹 [QA] QA 반영
  components/bar/Bar.tsx
  components/button/FloatingBtn.tsx
  components/detail/button/BtnFooter.tsx
  components/detail/category/Category.style.tsx
  components/vote/ABVoteItem.style.tsx
  components/vote/ABVoteItem.tsx
  domains/community/topic/AllTopicCards.style.tsx
  domains/community/topic/AllTopicCards.tsx
  domains/webtoon/home/TopicBanners.tsx
  domains/webtoon/home/Weekly.style.tsx
  pages/user/signin.tsx
Labels: v0.2, design

#179 🥅 [에러 핸들링] API 에러 핸들링 추가
  components/vote/ABVoteItem.tsx
  components/vote/ChiceVoteItem.tsx
  domains/community/topic/AllTopicCards.tsx
  domains/community/topic/TopicCards.tsx
  domains/webtoon/detail/Comment.tsx
  domains/webtoon/detail/Detail.tsx
  types/topics-type.d.ts
Labels: bug, enhancement, v0.2

#181 ✨ [인물/커플 상세페이지] 인물/커플 탑승하기
  apis/queryKeys.ts
  apis/webtoons.ts
  domains/community/character/CharacterDetailPage.style.tsx
  domains/community/character/CharacterDetailPage.tsx
  domains/community/character/CharacterVoteModal.style.tsx
  domains/community/character/CharacterVoteModal.tsx
  pages/community/character/[id].tsx
Labels: feature, v0.2

#183 ✨ [댓글] 좋아요 버튼 API 연동
  apis/comments.ts
  assets/icons/HeartIcon.tsx
  components/button/FavoriteBtn.tsx
  components/button/FloatingBtn.tsx
  domains/webtoon/detail/Comment.tsx
Labels: feature, v0.2

#184 [hotfix]: 초이스 투표 로그인 에러핸들링
  components/vote/ChiceVoteItem.tsx
Labels: bug, v0.2

#185 ✨ [모달] 코인 부족할 때 모달 생성
  assets/icons/antcoin_bg_gray.svg
  assets/icons/index.ts
  components/modal/coin/NotEnoughCoin.style.tsx
  components/modal/coin/NotEnoughCoin.tsx
  components/modal/vote/Modal.tsx
  domains/community/character/CharacterVoteModal.tsx
Labels: v0.2, component

#186 🩹 [마이페이지] 이름 수정 API 변경
  apis/user.ts
  domains/user/mypage/edit/EditImg.tsx
  pages/community/character/[id].tsx
  pages/user/mypage/edit.tsx
  pages/webtoon/[id].tsx
Labels: enhancement, v0.2

#187 🐛 [마이페이지] 프로필 이름 수정 에러 해결
  domains/user/mypage/MyPage.style.tsx
  domains/user/mypage/edit/EditName.style.tsx
  domains/user/mypage/edit/EditName.tsx
  pages/user/mypage/edit.tsx
Labels: bug, v0.2

#190 :fire:[fix]: QA - [AB투표카드, A/B카드 radius값 수정] 2개 이슈 해결
  components/vote/ABVoteItem.style.tsx
  components/vote/ABVoteItem.tsx
Labels: bug, v0.2, design

#191 :fire:[fix]: QA - 렌더처리 이슈, 슬라이더 padding이슈 해결
  components/detail/button/BtnFooter.style.tsx
  components/detail/category/Category.style.tsx
  components/detail/category/CategorySlider.tsx
  domains/webtoon/detail/Comment.tsx
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
Labels: bug, v0.2, design
