Repository depromeet/antoon_web, pull requests merged in 2022-05, with the labels that each got.

#49 :fire:[feature]/reply input component
  components/Row.tsx
  components/bar/Bar.tsx
  components/detail/commentTextInput/CommentTextInput.style.tsx
  components/detail/commentTextInput/CommentTextInput.tsx
  components/detail/tabs/Tabs.style.tsx
  components/detail/tabs/Tabs.tsx
  domains/webtoon/detail/Comment.style.tsx
  domains/webtoon/detail/Comment.tsx
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
  pages/webtoon/[id].tsx
  styles/themes/themes.ts
Labels: help wanted, feature, v0.1, component

#50 :fire:[bug]: Add style ReplyComponent
  components/detail/commentTextInput/CommentTextInput.style.tsx
  pages/webtoon/[id].tsx
Labels: bug, feature, v0.1, component, design

#51 ✨ [홈 페이지] 요일별 컴포넌트
  components/detail/commentTextInput/CommentTextInput.style.tsx
  components/icon/ScoreChangeIcon.tsx
  domains/webtoon/detail/Comment.style.tsx
  domains/webtoon/home/Genres.style.tsx
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/Home.tsx
  domains/webtoon/home/Popular.style.tsx
  domains/webtoon/home/Popular.tsx
  domains/webtoon/home/RealTimeChart.style.tsx
  domains/webtoon/home/RealTimeChart.tsx
  domains/webtoon/home/Recommendation.style.tsx
  domains/webtoon/home/Weekly.style.tsx
  domains/webtoon/home/Weekly.tsx
  domains/webtoon/home/webtoons.mock.ts
  public/images/thumb_먹는인생.png
  public/images/thumb_세기말_풋사과_보습학원.png
  public/images/thumb_연애혁명.png
  public/images/thumbnail_먹는인생.jpeg
  styles/themes/themes.ts
Labels: feature, v0.1, component

#55 ✨ [마이페이지] 레이아웃 마크업
  assets/banners/MyPageBanner.tsx
  assets/icons/ArrowIcon.tsx
  assets/icons/BackIcon.tsx
  assets/icons/DeleteIcon.tsx
  assets/icons/GithubIcon.tsx
  assets/icons/HeartIcon.tsx
  assets/icons/Icon.tsx
  assets/icons/LabelIcon.tsx
  assets/icons/LogoIcon.tsx
  assets/icons/ScoreChangeIcon.tsx
  assets/icons/SearchIcon.tsx
  assets/icons/StarIcon.tsx
  assets/icons/StockIcon.tsx
  assets/images/DefaultProfileImg.tsx
  components/button/FavoriteBtn.tsx
  components/layout/Header.tsx
  components/layout/SearchBar.tsx
  domains/search/Search.tsx
  domains/user/mypage/EditName.style.tsx
  domains/user/mypage/EditName.tsx
  domains/user/mypage/EditProfileImg.style.tsx
  domains/user/mypage/EditProfileImg.tsx
  domains/user/mypage/MyPage.style.tsx
  domains/user/mypage/MyPage.tsx
  domains/user/signin/Intro.tsx
  domains/webtoon/home/RealTimeChart.tsx
  pages/user/mypage.tsx
Labels: feature, v0.1, component

#56 🐛 [사용자 프로필 이미지] 크기 변동 문제 해결
  components/image/UserProfile.style.tsx
  components/image/UserProfile.tsx
  domains/webtoon/detail/Comment.tsx
Labels: bug, v0.1, component

#58 🐛 [사용자 프로필 이미지] default size 에서 props 값으로 변경
  components/image/UserProfile.style.tsx
  components/image/UserProfile.tsx
  domains/webtoon/detail/Comment.tsx
Labels: bug, v0.1, component

#60 ✨[웹툰 리스트]: 웹툰 리스트 api 연결 예제
  apis/index.ts
  apis/queryKeys.ts
  apis/webtoons.ts
  package.json
  pages/_app.tsx
  pages/index.tsx
  yarn.lock
Labels: v0.1, setting

#61 ✨ [로그인] 로그인 임시 설정
  domains/user/signin/SignInMain.style.tsx
  domains/user/signin/SignInMain.tsx
  domains/user/signin/SocialSignIn.tsx
  domains/user/signin/kakao/KaKao.style.tsx
  domains/user/signin/kakao/Kakao.tsx
  pages/user/signin.tsx
Labels: feature, v0.1

#63 💄 [테마] 디자인 시스템, 폰트 설정
  apis/.gitkeep
  assets/icons/ScoreChangeIcon.tsx
  assets/images/LoginImg.tsx
  components/charts/chart-utils.ts
  components/charts/composables/Chart_Visualizer.ts
  components/detail/category/Category.style.tsx
  components/detail/commentTextInput/CommentTextInput.style.tsx
  components/detail/tabs/Tabs.style.tsx
  components/image/Thumbnail.style.tsx
  components/layout/Layout.tsx
  components/layout/SearchBar.style.tsx
  domains/user/signin/Intro.style.tsx
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/home/Genres.style.tsx
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/Popular.style.tsx
  domains/webtoon/home/RealTimeChart.style.tsx
  domains/webtoon/home/Recommendation.style.tsx
  domains/webtoon/home/Weekly.style.tsx
  public/fonts/woff2/Pretendard-Black.woff2
  public/fonts/woff2/Pretendard-Bold.woff2
  public/fonts/woff2/Pretendard-ExtraBold.woff2
  public/fonts/woff2/Pretendard-ExtraLight.woff2
  public/fonts/woff2/Pretendard-Light.woff2
  public/fonts/woff2/Pretendard-Medium.woff2
  public/fonts/woff2/Pretendard-Regular.woff2
  public/fonts/woff2/Pretendard-SemiBold.woff2
  public/fonts/woff2/Pretendard-Thin.woff2
  styles/globalstyles/GlobalStyle.tsx
  styles/themes/themes.ts
Labels: v0.1, component, design

#66 ✨ [헤더] 각 페이지 별 헤더 대응
  .storybook/preview.js
  assets/banners/MyPageBanner.tsx
  assets/icons/ChebronRightIcon.tsx
  assets/icons/LogoIcon.tsx
  assets/icons/SearchIcon.tsx
  assets/images/KakaoLoginImg.tsx
  assets/images/LoginImg.tsx
  assets/images/ProfileDefaultImg.tsx
  assets/images/SearchDefaultImg.tsx
  assets/images/SignInDefaultImg.tsx
  components/image/UserProfile.tsx
  components/layout/Header.style.tsx
  components/layout/Header.tsx
  components/layout/Header/Header.style.tsx
  components/layout/Header/Header.tsx
  components/layout/Header/HeaderLeftMenu.style.tsx
  components/layout/Header/HeaderLeftMenu.tsx
  components/layout/Header/HeaderRightMenu.style.tsx
  components/layout/Header/HeaderRightMenu.tsx
  components/layout/Header/SearchBar.style.tsx
  components/layout/Header/SearchBar.tsx
  domains/user/mypage/EditProfileImg.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/search.tsx
  pages/user/mypage.tsx
  pages/user/signin.tsx
  pages/user/signup/policy.tsx
  pages/webtoon/[id].tsx
  public/fonts/woff2/Pretendard-Black.woff2
  public/fonts/woff2/Pretendard-Bold.woff2
  public/fonts/woff2/Pretendard-ExtraBold.woff2
  public/fonts/woff2/Pretendard-ExtraLight.woff2
  public/fonts/woff2/Pretendard-Light.woff2
  public/fonts/woff2/Pretendard-Medium.woff2
  public/fonts/woff2/Pretendard-Regular.woff2
  public/fonts/woff2/Pretendard-SemiBold.woff2
  public/fonts/woff2/Pretendard-Thin.woff2
  styles/GlobalStyle.tsx
  styles/globalstyles/GlobalStyle.tsx
Labels: feature, v0.1, component

#69 ✨ [마이 페이지] 스크린 디자인 반영
  assets/banners/MyPageBanner.tsx
  assets/images/ProfileDefaultImg.tsx
  components/layout/Header/Header.tsx
  components/layout/Header/HeaderRightMenu.tsx
  components/line/CustomHr.style.tsx
  components/line/CustomHr.tsx
  domains/user/mypage/EditName.style.tsx
  domains/user/mypage/EditProfileImg.tsx
  domains/user/mypage/MyPage.style.tsx
  domains/user/mypage/MyPage.tsx
  package.json
  pages/index.tsx
  styles/GlobalStyle.tsx
  yarn.lock
Labels: v0.1, component, design

#71 :fire:[feature] : 디자인 수정 및 상세 푸터 작성
  assets/icons/Icon.tsx
  assets/icons/StockIcon.tsx
  assets/icons/YeonJaeIcon.tsx
  components/charts/chart-utils.ts
  components/charts/composables/Chart_Visualizer.ts
  components/detail/button/BtnFooter.style.tsx
  components/detail/button/BtnFooter.tsx
  components/detail/button/UpDownBtn.style.tsx
  components/detail/button/UpDownBtn.tsx
  components/detail/category/Category.style.tsx
  components/detail/category/CategoryCard.tsx
  components/detail/category/CategorySlider.tsx
  constants/icon-constants.ts
  domains/webtoon/detail/Comment.data.ts
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
  pages/webtoon/[id].tsx
  public/assets/jenre10.png
  public/assets/jenre_1.png
  public/assets/jenre_10.png
  public/assets/jenre_2.png
  public/assets/jenre_3.png
  public/assets/jenre_4.png
  public/assets/jenre_5.png
  public/assets/jenre_6.png
  public/assets/jenre_7.png
  public/assets/jenre_8.png
  public/assets/jenre_9.png
  public/assets/platform_KAKAO.png
  public/assets/platform_LEZHIN.png
  public/assets/platform_NAVER.png
  styles/themes/themes.ts
Labels: feature, v0.1, component

#70 ✨ [홈 페이지] 웹툰 랭킹 api 연결
  .github/workflows/deploy.yml
  apis/queryKeys.ts
  apis/webtoons.ts
  domains/webtoon/home/RealTimeChart.tsx
  next.config.js
  pages/index.tsx
  types/webtoon-type.d.ts
Labels: feature, v0.1

#72 :fire:[bug]: Update Detail Footer css
  components/detail/button/BtnFooter.style.tsx
  components/detail/button/UpDownBtn.style.tsx
Labels: bug, enhancement, feature, v0.1

#77 ✨ [홈 페이지] 장르별 웹툰 수정
  apis/index.ts
  apis/queryKeys.ts
  apis/webtoons.ts
  components/modal/onboard/Modal.tsx
  domains/webtoon/home/Genres.style.tsx
  domains/webtoon/home/Genres.tsx
  next.config.js
  pages/_app.tsx
  pages/index.tsx
  styles/themes/themes.ts
Labels: enhancement, feature, v0.1

#80 :ambulance: [프로젝트 세팅] 로깅 추가
  .github/workflows/deploy.yml
  .gitignore
  apis/index.ts
  apis/webtoons.ts
  components/modal/onboard/Modal.tsx
  domains/user/policy/checkbox/Checkbox.stories.tsx
  domains/webtoon/home/Genres.style.tsx
  domains/webtoon/home/Genres.tsx
  domains/webtoon/home/Home.stories.tsx
  domains/webtoon/home/RealTimeChart.tsx
  mixpanel.ts
  next.config.js
  package.json
  pages/_error.js
  pages/index.tsx
  pages/search.tsx
  pages/user/mypage.tsx
  pages/user/signin.tsx
  pages/user/signup/Policy.tsx
  pages/webtoon/[id].tsx
  sentry.client.config.js
  sentry.server.config.js
  serverless.yml
  types/webtoon-type.d.ts
  yarn.lock
Labels: bug, v0.1, chore

#81 ✨ [홈 페이지] 홈 배너 추가
  apis/api.ts
  apis/webtoons.ts
  assets/banners/HomePageBanner.tsx
  components/button/GoToRideBtn.stories.tsx
  components/button/GoToRideBtn.tsx
  domains/webtoon/home/Home.style.tsx
  domains/webtoon/home/Home.tsx
  domains/webtoon/home/RealTimeChart.style.tsx
  domains/webtoon/home/RealTimeChart.tsx
  hooks/useSmoothScroll.ts
  pages/_app.tsx
  pages/index.tsx
Labels: v0.1, component

#82 ✨ [홈 페이지] 연령대별 추천 웹툰
  domains/webtoon/home/Recommendation.stories.tsx
  domains/webtoon/home/Recommendation.style.tsx
  domains/webtoon/home/Recommendation.tsx
Labels: v0.1, component

#83 ✨ [사용자 인증] 토큰 값 쿠키 관리 기능 생성
  apis/api.ts
  package.json
  pages/user/signin.tsx
  yarn.lock
Labels: enhancement, feature, v0.1

#84 ✅ [테스트] 버튼, 헤더 스토리북 생성
  .storybook/preview-head.html
  .storybook/preview.js
  components/button/FavoriteBtn.stories.tsx
  components/button/FloatingBtn.stories.tsx
  components/layout/Header/Header.stories.tsx
Labels: v0.1, component

#85 🛠 [코드 포맷] 스타일 및 서식 수정
  .vscode/settings.json
  README.md
  assets/banners/MyPageBanner.tsx
  assets/icons/BackIcon.tsx
  assets/icons/ChebronRightIcon.tsx
  assets/icons/DeleteIcon.tsx
  assets/icons/LogoIcon.tsx
  assets/icons/SearchIcon.tsx
  assets/images/KakaoLoginImg.tsx
  assets/images/SearchDefaultImg.tsx
  assets/images/SignInDefaultImg.tsx
  components/button/FavoriteBtn.tsx
  components/detail/category/Category.style.tsx
  domains/search/Search.data.ts
  domains/search/Search.tsx
  domains/user/mypage/MyPage.tsx
  domains/webtoon/detail/Comment.style.tsx
  domains/webtoon/detail/Comment.tsx
  domains/webtoon/detail/Detail.style.tsx
  pages/search.tsx
  public/images/jenre10.png
  public/images/jenre_1.png
  public/images/jenre_10.png
  public/images/jenre_2.png
  public/images/jenre_3.png
  public/images/jenre_4.png
  public/images/jenre_5.png
  public/images/jenre_6.png
  public/images/jenre_7.png
  public/images/jenre_8.png
  public/images/jenre_9.png
  public/images/platform_KAKAO.png
  public/images/platform_LEZHIN.png
  public/images/platform_NAVER.png
  utils/autoComplete.ts
Labels: v0.1, chore

#86 💄 [헤더] 토큰 수정 사항, 링크 공유 기능 반영
  assets/icons/ShareIcon.tsx
  assets/images/ProfileDefaultImg.tsx
  components/layout/Header/Header.tsx
  components/layout/Header/HeaderRightMenu.tsx
  pages/index.tsx
Labels: enhancement, feature, v0.1, component

#87 ✨ [홈 페이지] 요일별 웹툰 API 연동
  apis/webtoons.ts
  components/OnError.tsx
  components/image/default.ts
  domains/webtoon/home/RealTimeChart.style.tsx
  domains/webtoon/home/RealTimeChart.tsx
  domains/webtoon/home/Weekly.style.tsx
  domains/webtoon/home/Weekly.tsx
  domains/webtoon/home/WeeklyWebtoons.tsx
  package.json
  pages/index.tsx
  types/webtoon-type.d.ts
  yarn.lock
Labels: feature, v0.1

#88 🥅 [에러 처리] 에러 바운더리 추가
  components/ErrorBoundary.tsx
  domains/webtoon/home/RealTimeChart.tsx
  domains/webtoon/home/WeeklyWebtoons.tsx
Labels: enhancement, v0.1

#89 🩹 [홈 페이지/QA] 요일별 웹툰 요일 순서 변경
  domains/webtoon/home/Weekly.tsx
Labels: bug, v0.1

#90 ✨ [홈 페이지] 상승중 웹툰 api 연동
  apis/queryKeys.ts
  apis/webtoons.ts
  domains/webtoon/home/Home.tsx
  domains/webtoon/home/Popular.tsx
  domains/webtoon/home/Rising.style.tsx
  domains/webtoon/home/Rising.tsx
  pages/index.tsx
  types/webtoon-type.d.ts
Labels: feature, v0.1

#91 ♻️ [리팩터링] 변수명 수정
  domains/search/Search.tsx
  pages/user/signin.tsx
  utils/autoComplete.ts
Labels: v0.1, chore

#92 ✨ [상세 페이지] 댓글 리스트 조회 API 연결
  apis/comments.ts
  apis/queryKeys.ts
  components/detail/commentTextInput/CommentTextInput.tsx
  domains/webtoon/detail/Comment.style.tsx
  domains/webtoon/detail/Comment.tsx
  pages/webtoon/[id].tsx
  types/comments-type.ts
Labels: feature, v0.1

#93 ♻️ [상세 페이지] 댓글 리스트 조회 코드 리팩터링
  apis/comments.ts
  apis/queryKeys.ts
  components/detail/commentTextInput/CommentTextInput.tsx
  domains/webtoon/detail/Comment.tsx
  pages/webtoon/[id].tsx
Labels: v0.1, chore

#94 :fire:[feature] Add Detail DataFetching
  apis/webtoons.ts
  components/charts/composables/Chart_Visualizer.ts
  components/detail/category/CategoryCard.tsx
  components/detail/category/CategorySlider.tsx
  domains/webtoon/detail/Detail.style.tsx
  domains/webtoon/detail/Detail.tsx
  pages/webtoon/[id].tsx
  types/webtoon-type.d.ts
  utils/css-util.ts
Labels: v0.1, component

#95 ✨ [홈 페이지] 장르별 top3 api 연동
  apis/queryKeys.ts
  apis/webtoons.ts
  domains/webtoon/home/Genres.tsx
  pages/index.tsx
  styles/themes/themes.ts
  types/webtoon-type.d.ts
Labels: feature, v0.1

#96 ✨ [회원가입] 정책 동의 페이지 마크업
  .storybook/main.js
  assets/icons/arrow_right.svg
  assets/icons/check_circle_filled.svg
  assets/icons/check_circle_line.svg
  assets/icons/index.ts
  assets/icons/logo_big.svg
  domains/user/policy/checkbox/Checkbox.stories.tsx
  domains/user/policy/checkbox/Checkbox.tsx
  domains/user/signup/policy/Checkbox.stories.tsx
  domains/user/signup/policy/Checkbox.style.tsx
  domains/user/signup/policy/Checkbox.tsx
  domains/user/signup/policy/Policy.style.tsx
  domains/user/signup/policy/StartButton.style.tsx
  domains/user/signup/policy/StartButton.tsx
  next.config.js
  package.json
  pages/user/signup/Policy.tsx
  types/svg.d.ts
  yarn.lock
Labels: v0.1, component

#98 📦 [프로젝트 세팅] hotjar 추가
  pages/_app.tsx
Labels: v0.1, chore

#97 ✨ [홈 페이지] 연령대별 웹툰 api 연동
  apis/queryKeys.ts
  apis/webtoons.ts
  domains/webtoon/home/Recommendation.stories.tsx
  domains/webtoon/home/Recommendation.style.tsx
  domains/webtoon/home/Recommendation.tsx
  pages/index.tsx
  types/webtoon-type.d.ts
Labels: feature, v0.1

#99 ✨ [검색] API 연동 완료
  assets/icons/DeleteIcon.tsx
  components/layout/Header/HeaderRightMenu.tsx
  components/layout/Header/SearchBar.tsx
  domains/search/AutoComplet.style.tsx
  domains/search/AutoCompletList.tsx
  domains/search/Search.style.tsx
  domains/search/Search.tsx
  domains/search/SearchBar.style.tsx
  domains/search/SearchBar.tsx
  domains/search/SearchResult.style.tsx
  domains/search/SearchResult.tsx
  pages/search.tsx
  states/.gitkeep
  states/search.ts
  types/webtoon-type.d.ts
Labels: enhancement, feature, v0.1

#103 fix bug css
  domains/webtoon/detail/Detail.style.tsx
Labels: bug
